name: backend

on:
  push:
    branches: [ fg-actions ]

jobs:
  docker:
    runs-on: docker
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install docker???
        run: apt update && apt install docker.io -y

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: login
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: build
        run: docker build -t $DOCKER_USER/splatnet-backend:latest .

      - name: push
        run: docker push $DOCKER_USER/splatnet-backend:latest